In [2]:
from dataloader_ego4d import Ego4DVideoFolder
sample = Ego4DVideoFolder(root= '/iris/u/nivsiyer/ego4d/videos2', manifest_csv='/iris/u/nivsiyer/ego4d/videos2/manifest.csv', clip_size=10, step_size=1, is_val=False,
                          transform_pre=None, transform_post=None,
                 augmentation_mappings_json=None, augmentation_types_todo=None,
                 is_test=False, robot_demo_transform=None)


for item in sample:
    print(item)
    break

tf.Tensor(
[[[[[0.47843137 0.5921569  0.16078432]
    [0.45490196 0.5686275  0.14509805]
    [0.49019608 0.5921569  0.19607843]
    ...
    [0.34901962 0.4        0.09019608]
    [0.41960785 0.38431373 0.16862746]
    [0.48235294 0.40784314 0.23921569]]

   [[0.47843137 0.5921569  0.16078432]
    [0.45490196 0.5686275  0.14509805]
    [0.49019608 0.5921569  0.19607843]
    ...
    [0.30588236 0.3372549  0.05098039]
    [0.3529412  0.30588236 0.10196079]
    [0.62352943 0.5372549  0.3764706 ]]

   [[0.4627451  0.5764706  0.15294118]
    [0.44705883 0.56078434 0.14509805]
    [0.47843137 0.5882353  0.19607843]
    ...
    [0.5137255  0.5137255  0.2627451 ]
    [0.5529412  0.4862745  0.3137255 ]
    [0.7607843  0.65882355 0.5294118 ]]

   ...

   [[0.5019608  0.53333336 0.58431375]
    [0.6117647  0.6392157  0.7019608 ]
    [0.6        0.627451   0.7019608 ]
    ...
    [0.78039217 0.7019608  0.60784316]
    [0.7372549  0.6509804  0.5686275 ]
    [0.91764706 0.827451   0.75686276]]

   [[

In [1]:
import pandas as pd