In [1]:
# import av
# import torch
# import numpy as np
# import os
# import h5py
# import pandas as pd

# import os

# import io
# import json
# import numpy as np
# import torchvision
# from transforms_video import *
# from tensorflow import *
# import torchvision
# from transforms_video import *
# import tensorflow as tf
# import pdb
# import time

# from dataloader_parsed import Augmentor
# from tensorflow.keras.layers import Permute 
# from collections import namedtuple, defaultdict, Counter
# import json

# ListData = namedtuple('ListData', ['label', 'vidpath', 'start_frame', 'end_frame'])
# FRAMERATE = 12  # default value 

In [87]:
# class Ego4DVideoFolder():

#     def __init__(self, root, manifest_csv, clip_size=2, step_size=0, is_val=False,
#                  transform_pre=None, transform_post=None,
#                  augmentation_mappings_json=None, augmentation_types_todo=None,
#                  is_test=False, robot_demo_transform=None): # add back args later
        
#         vidpath = "/iris/u/nivsiyer/ego4d/videos"
#         self.csv = pd.read_csv(manifest_csv)
#         self.labels = self.csv['label'].unique()
#         self.num_tasks = len(self.labels)
        
#         self.is_val = is_val

#         self.root = root
#         self.transform_pre = transform_pre
#         self.transform_post = transform_post
#         self.im_size = 120 #default
#         self.batch_size = 24 #args.batch_size

#         self.augmentor = Augmentor(augmentation_mappings_json,
#                                    augmentation_types_todo)

#         self.traj_length = clip_size
#         self.step_size = step_size
#         self.similarity = True #args.similarity
#         self.add_demos = 60 #args.add_demos 
        
#         classes = []
#         self.classes = classes
#         num_occur = defaultdict(int)
                            
#         print("Number of human videos: ", len(self.csv), "Total:", self.__len__())

            
#     def process_video(self, item):
#          # Open video file
#         try: 
#             reader = av.open(item.path)
#         except:
#             print("Issue with opening the video, path:", item.path)
#             assert(False)

#         try:
#             imgs = []
#             imgs = [f.to_rgb().to_ndarray() for f in reader.decode(video=0)]
#         except (RuntimeError, ZeroDivisionError) as exception:
#             print('{}: WEBM reader cannot open {}. Empty '
#                   'list returned.'.format(type(exception).__name__, item.path))
#         orig_imgs = np.array(imgs).copy() 

#         p = np.array(imgs)
#         imgs = self.transform_pre(imgs)
#         imgs, label = self.augmentor(imgs, item.label)
#         imgs = self.transform_post(imgs)

#         num_frames = len(imgs)        
#         if self.nclips > -1:
#             num_frames_necessary = self.traj_length * self.nclips * self.step_size
#         else:
#             num_frames_necessary = num_frames
#         offset = 0
#         if num_frames_necessary < num_frames:
#             # If there are more frames, then sample starting offset.
#             diff = (num_frames - num_frames_necessary)
#             # temporal augmentation
#             offset = np.random.randint(0, diff)

#         imgs = imgs[offset: num_frames_necessary + offset: self.step_size]
#         if len(imgs) < (self.traj_length * self.nclips):
#             imgs.extend([imgs[-1]] *
#                         ((self.traj_length * self.nclips) - len(imgs)))

#         data = tf.stack(imgs)
#         data = tf.transpose(tf.convert_to_tensor(data), perm=[0, 2, 3, 1])
#         return data
    
            
#     def __getitem__(self, indices = None):
        
#         def getindices():
#           anchor = random.choice(self.labels) 
#           positives = self.csv[self.csv['label'] == anchor].sample(n = 2)
#           neg = self.csv[self.csv['label'] != anchor].sample(n=1)
#           return positives.iloc[0], positives.iloc[1], neg.iloc[0]
        
#         def process(video):
#           vidpath = video.vidpath
#           ims = []
#           # print("Version:", tf.__version__)
#           load1 = tf.keras.preprocessing.image.load_img(
#                   vidpath+f"/{video.start_frame:07}.jpg",
#                   grayscale=False,
#                   color_mode='rgb',
#               )

#           ims.append(load1)
#           load2 = tf.keras.preprocessing.image.load_img(
#                    vidpath+f"/{video.end_frame:07}.jpg",
#                   grayscale=False,
#                   color_mode='rgb',
#               )
#           ims.append(load2)
          
#           ims = tf.cast(tf.stack([tf.keras.preprocessing.image.img_to_array(x) for x in ims], 0), tf.float32) / 255.0
#           return ims

              
#         item, anchor, neg = getindices()
        
#         pos_data = process(item)
#         anchor_data  =  process(anchor)
#         neg_data =  process(neg)
#         return tf.stack([pos_data, anchor_data, neg_data], 0) #){'pos': pos_data, 'anchor': anchor_data, 'neg': neg_data}

#     def __len__(self):
#         return len([name for name in os.listdir(self.root) if os.path.isdir(os.path.join(self.root, name))])
    
#     def __call__(self):
#         while True:
#             yield 0.0


In [88]:
from dataloader_ego4d import Ego4DVideoFolder
sample = Ego4DVideoFolder(root= '/iris/u/nivsiyer/ego4d/videos2', manifest_csv='/iris/u/nivsiyer/ego4d/videos2/manifest.csv', clip_size=10, step_size=1, is_val=False,
                          transform_pre=None, transform_post=None,
                 augmentation_mappings_json=None, augmentation_types_todo=None,
                 is_test=False, robot_demo_transform=None)

Number of human videos:  15511 Total: 948


In [89]:
for item in sample:
    print(item)
    break

[[[[[0.56078434 0.564705908 0.541176498]
    [0.552941203 0.556862772 0.53725493]
    [0.564705908 0.572549045 0.56078434]
    ...
    [0.576470613 0.494117647 0.482352942]
    [0.580392182 0.501960814 0.474509805]
    [0.498039216 0.419607848 0.384313732]]

   [[0.576470613 0.580392182 0.556862772]
    [0.6 0.603921592 0.58431375]
    [0.6 0.607843161 0.596078455]
    ...
    [0.643137276 0.568627477 0.552941203]
    [0.6 0.525490224 0.498039216]
    [0.521568656 0.454901963 0.41568628]]

   [[0.576470613 0.572549045 0.552941203]
    [0.631372571 0.635294139 0.615686297]
    [0.623529434 0.631372571 0.619607866]
    ...
    [0.666666687 0.615686297 0.592156887]
    [0.615686297 0.564705908 0.533333361]
    [0.521568656 0.482352942 0.443137258]]

   ...

   [[0.172549024 0.160784319 0.141176477]
    [0.203921571 0.192156866 0.172549024]
    [0.223529413 0.211764708 0.192156866]
    ...
    [0.556862772 0.647058845 0.709803939]
    [0.6 0.709803939 0.75686276]
    [0.725490212 0.8431372

In [54]:
def getindices(thing):
          anchor = random.choice(thing.labels) 
          print(anchor)
          positives = thing.csv[thing.csv['label'] == anchor].sample(n = 2)
          print(type(positives))
          neg = thing.csv[thing.csv['label'] != anchor].sample(n=1)
          return positives.iloc[0], positives.iloc[1], neg

In [56]:
p1, p2, n = getindices(sample)

"squeeze_juice_from_a_fruit_(lemon,_lime,_etc.)"
<class 'pandas.core.frame.DataFrame'>


In [58]:
p1.vidpath

'/iris/u/nivsiyer/ego4d/videos2/16d55886-6e1e-4195-9918-12dc4568320e'

In [20]:
sample.labels = sample.csv['label'].unique()

In [27]:
'operate_a_water_hose' in sample.labels

True

In [32]:
sample.csv['label'] == 'operate_a_water_hose'

0        False
1        False
2        False
3        False
4        False
         ...  
15506    False
15507    False
15508    False
15509    False
15510    False
Name: label, Length: 15511, dtype: bool

In [76]:
p1

Unnamed: 0                                                  8424
label           "squeeze_juice_from_a_fruit_(lemon,_lime,_etc.)"
vidpath        /iris/u/nivsiyer/ego4d/videos2/16d55886-6e1e-4...
start_frame                                                88241
end_frame                                                  89100
Name: 8424, dtype: object